build: off

environment:
  nodejs_version: "Stable"

install:
  - node -v
  - git submodule update --init --recursive
  - yarn install
  - yarn install-node-obs
  - yarn ci:compile

test_script:
  - yarn test -- -v
