build: off

environment:
  nodejs_version: "8.9.0"

install:
  - ps: Install-Product node 8.9.0 x64
  - node -v
  - git submodule update --init --recursive
  - yarn install
  - yarn install-node-obs
  - yarn ci:compile

test_script:
  - yarn test -- -v
